In [1]:
import pandas as pd
import re
import tensorflow as tf
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import nltk.translate.bleu_score as bleu
import random
import string
from sklearn.model_selection import train_test_split
import os
import time
import googletrans 
from googletrans import *

ModuleNotFoundError: No module named 'googletrans'

In [2]:
eng_tel=pd.read_csv('eng_tel.csv')
eng_tel.head()

English  \
0  politicians do not have permission to do what ...   
1         I'd like to tell you about one such child,   
2  This percentage is even greater than the perce...   
3  what we really mean is that they're bad at not...   
4  .The ending portion of these Vedas is called U...   

                                              Telugu  
0  రాజకీయ నాయకులకు చేయవలసినది చేయడానికి అనుమతి లేదు.  
1  అలాంటి ఒక పిల్లల గురించి నేను మీకు చెప్పాలనుకు...  
2           ఈ శాతం భారతదేశంలో ఉన్న శాతం కంటే ఎక్కువ.  
3  మేము నిజంగా అర్థం ఏమిటంటే వారు శ్రద్ధ చూపకపోవడ...  
4        .ఈ వేదాల ముగింపు భాగాన్ని ఉపనిషత్తు అంటారు.

In [3]:
eng_tel.dropna(inplace=True)
eng_tel.shape

(5615, 2)

In [4]:
exclude = set(string.punctuation) # Set of all special characters
remove_digits = str.maketrans('', '', string.digits) # Set of all digits

In [5]:
def preprocess(text):
    '''for english'''
    text = text.lower() # lower casing
    text = re.sub("'", '', text) # remove the quotation marks if any
    text = ''.join(ch for ch in text if ch not in exclude)
    text = text.translate(remove_digits) # remove the digits
    text = text.strip() #whitespace
    text = re.sub(" +", " ", text) # remove extra spaces
    text = '<start> ' + text + ' <end>'
    return text

In [6]:
def preprocess_tel(text):
    '''Function to preprocess Telugu sentence'''
    text = re.sub("'", '', text) # remove the quotation marks if any
    text = ''.join(ch for ch in text if ch not in exclude)
    text = text.strip()
    text = re.sub(" +", " ", text) # remove extra spaces
    text = '<start> ' + text + ' <end>'
    return text

In [7]:
eng_tel['English'] = eng_tel['English'].apply(preprocess)
eng_tel['Telugu'] = eng_tel['Telugu'].apply(preprocess_tel)


eng_tel.head()

English  \
0  <start> politicians do not have permission to ...   
1  <start> id like to tell you about one such chi...   
2  <start> this percentage is even greater than t...   
3  <start> what we really mean is that theyre bad...   
4  <start> the ending portion of these vedas is c...   

                                              Telugu  
0  <start> రాజకీయ నాయకులకు చేయవలసినది చేయడానికి అ...  
1  <start> అలాంటి ఒక పిల్లల గురించి నేను మీకు చెప...  
2  <start> ఈ శాతం భారతదేశంలో ఉన్న శాతం కంటే ఎక్కు...  
3  <start> మేము నిజంగా అర్థం ఏమిటంటే వారు శ్రద్ధ ...  
4  <start> ఈ వేదాల ముగింపు భాగాన్ని ఉపనిషత్తు అంట...

In [8]:
def tokenize(lang):
    
    lang_tokenizer = tf.keras.preprocessing.text.Tokenizer(filters='')
    lang_tokenizer.fit_on_texts(lang)

    tensor = lang_tokenizer.texts_to_sequences(lang)

    tensor = tf.keras.preprocessing.sequence.pad_sequences(tensor,padding='post',maxlen=20,dtype='int32')
    print(tensor,lang_tokenizer.document_count)

    return tensor, lang_tokenizer

In [9]:
def load_dataset():

    input_tensor, inp_lang_tokenizer = tokenize(eng_tel['English'].values)
    target_tensor, targ_lang_tokenizer = tokenize(eng_tel['Telugu'].values)

    return input_tensor, target_tensor, inp_lang_tokenizer, targ_lang_tokenizer

In [10]:
len(eng_tel['English'].values)

5615

In [11]:
input_tensor, target_tensor, inp_lang, targ_lang = load_dataset()

[[    1  1513    72 ...     0     0     0]
 [    1  1780    64 ...     0     0     0]
 [    1    15  1313 ...     0     0     0]
 ...
 [    1     3  2540 ...  5138  4012     2]
 [   28 13168 13169 ... 13171    65     2]
 [    1    39  4827 ...     0     0     0]] 5615
[[    1    78  6631 ...     0     0     0]
 [    1   599     7 ...     0     0     0]
 [    1     5   127 ...     0     0     0]
 ...
 [    1 19016 19017 ...     0     0     0]
 [19021 19022   163 ...   249    67     2]
 [    1     5   105 ...     0     0     0]] 5615


In [12]:
max_length_targ, max_length_inp = target_tensor.shape[1], input_tensor.shape[1]

In [13]:
input_tensor_train, input_tensor_val, target_tensor_train, target_tensor_val = train_test_split(input_tensor, target_tensor, test_size=0.15)

print(len(input_tensor_train), len(target_tensor_train), len(input_tensor_val), len(target_tensor_val))

4772 4772 843 843


In [14]:
BUFFER_SIZE = len(input_tensor_train)
BATCH_SIZE = 16 #no of process in a single iteration 
N_BATCH = BUFFER_SIZE//BATCH_SIZE
embedding_dim = 128
units = 1024 # hidden states in rnn
steps_per_epoch = len(input_tensor_train)//BATCH_SIZE

vocab_inp_size =len(inp_lang.word_index.keys())
vocab_tar_size =len(targ_lang.word_index.keys())

dataset = tf.data.Dataset.from_tensor_slices((input_tensor_train, target_tensor_train)).shuffle(BUFFER_SIZE)
dataset = dataset.batch(BATCH_SIZE, drop_remainder=True)
print(vocab_inp_size)
# print(targ_lang.word_index.keys())
#print(inp_lang.word_index.keys())

13171


In [15]:
embeddings_index = dict()
# contain pre-trained word embeddings in the GloVe format
f = open(r'glove.6B.300d.txt',encoding='utf-8')

for line in f:
    
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

embedding_matrix = np.zeros((vocab_inp_size+1, 300))
print(embedding_matrix)
for word, i in inp_lang.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [16]:
class Encoder(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, enc_units, batch_sz):
        super(Encoder, self).__init__()
        #batch size of input data
        self.batch_sz = batch_sz
       
        self.enc_units = enc_units
        # english related data
        self.embedding = tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=embedding_dim, name="embedding_layer_encoder",trainable=False)
        #update the hidden step using the input based on embedding
        self.gru = tf.keras.layers.GRU(units, return_sequences=True, return_state=True, recurrent_activation='sigmoid', recurrent_initializer='glorot_uniform')
    # it says how the input data should flow using the gru it gives final hidden value    
    def call(self, x, hidden):
        x = self.embedding(x)
        output, state = self.gru(x, initial_state = hidden)
        return output, state
    
    def initialize_hidden_state(self):
        return tf.zeros((self.batch_sz, self.enc_units))

In [17]:
class Decoder(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, dec_units, batch_sz):
        super(Decoder, self).__init__()
        self.batch_sz = batch_sz
        self.dec_units = dec_units
        #telugu related data
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
        self.gru = tf.keras.layers.GRU(units, return_sequences=True, return_state=True, recurrent_activation='sigmoid', recurrent_initializer='glorot_uniform')
        #represents the word probability
        self.fc = tf.keras.layers.Dense(vocab_size)
        #predicts the next word
        

                # attention mechanism used to predict the best word
        self.W1 = tf.keras.layers.Dense(self.dec_units)
        self.W2 = tf.keras.layers.Dense(self.dec_units)
        self.V = tf.keras.layers.Dense(1)
# combines the attention mechanism, recurrent layer, and dense layers to generate the decoder's outpu
    def call(self, x, hidden, enc_output):

        hidden_with_time_axis = tf.expand_dims(hidden, 1)
        
        score = self.V(tf.nn.tanh(self.W1(enc_output) + self.W2(hidden_with_time_axis)))
        
        attention_weights = tf.nn.softmax(score, axis=1)
        
        context_vector = attention_weights * enc_output
        context_vector = tf.reduce_sum(context_vector, axis=1)
        
        x = self.embedding(x)
        
        x = tf.concat([tf.expand_dims(context_vector, 1), x], axis=-1)
        
        output, state = self.gru(x)
        
        output = tf.reshape(output, (-1, output.shape[2]))
        
        x = self.fc(output)
        
        return x, state, attention_weights
        
    def initialize_hidden_state(self):
        return tf.zeros((self.batch_sz, self.dec_units))

In [18]:
tf.keras.backend.clear_session()

encoder = Encoder(vocab_inp_size+1, 300, units, BATCH_SIZE)
decoder = Decoder(vocab_tar_size+1, embedding_dim, units, BATCH_SIZE)

In [8]:
def evaluate1(inp):
    
    translate = translator.translate(inp,dest = 'telugu')
    print(translate.text)

In [19]:
optimizer = tf.keras.optimizers.Adam()
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True,
                                                            reduction='none')
# for loss calculation for each and every epoch loss should decrease

def loss_function(real, pred):
    mask = tf.math.logical_not(tf.math.equal(real, 0))
    loss_ = loss_object(real, pred)

    mask = tf.cast(mask, dtype=loss_.dtype)
    loss_ *= mask
    

    return tf.reduce_mean(loss_)

In [20]:
@tf.function
#'''mixing of encoder and decoder and finding loss'''
#finding the prediction compute loss and update parameter using optimizer
def train_step(inp, targ, enc_hidden):
    loss = 0

    with tf.GradientTape() as tape:
        enc_output, enc_hidden = encoder(inp, enc_hidden)
        encoder.get_layer('embedding_layer_encoder').set_weights([embedding_matrix])
        dec_hidden = enc_hidden

        dec_input = tf.expand_dims([targ_lang.word_index['']] * BATCH_SIZE, 1) if '' in targ_lang.word_index else tf.expand_dims([0] * BATCH_SIZE, 1)

        for t in range(1, targ.shape[1]):
            predictions, dec_hidden, _ = decoder(dec_input, dec_hidden, enc_output)

            loss += loss_function(targ[:, t], predictions)

            dec_input = tf.expand_dims(targ[:, t], 1)

        batch_loss = (loss / int(targ.shape[1]))

        variables = encoder.trainable_variables + decoder.trainable_variables

        gradients = tape.gradient(loss, variables)

        optimizer.apply_gradients(zip(gradients, variables))

    return batch_loss


In [ ]:
EPOCHS = 25

for epoch in range(EPOCHS):
    start = time.time()

    enc_hidden = encoder.initialize_hidden_state()
    total_loss = 0

    for (batch, (inp, targ)) in enumerate(dataset.take(steps_per_epoch)):
#         print(start)
        batch_loss = train_step(inp, targ, enc_hidden)
        total_loss += batch_loss

    if batch % 100 == 0:
        print(f'Epoch {epoch+1} Batch {batch} Loss {batch_loss.numpy():.4f}')

    print(f'Epoch {epoch+1} Loss {total_loss/steps_per_epoch:.4f}')
    print(f'Time taken for 1 epoch {time.time()-start:.2f} sec\n')


Epoch 1 Loss 4.4368
Time taken for 1 epoch 643.23 sec

Epoch 2 Loss 4.1339
Time taken for 1 epoch 525.37 sec



In [ ]:
def evaluate(sentence):
  attention_plot = np.zeros((max_length_targ, max_length_inp))

  sentence = preprocess(sentence)

  inputs = [inp_lang.word_index[i] for i in sentence.split(' ')]
  inputs = tf.keras.preprocessing.sequence.pad_sequences([inputs],maxlen=20, padding='post')
  inputs = tf.convert_to_tensor(inputs)

  result = ''

  hidden = [tf.zeros((1, units))]
  enc_out, enc_hidden = encoder(inputs, hidden)

  dec_hidden = enc_hidden
  dec_input = tf.expand_dims([targ_lang.word_index['<start>']], 0)

  for t in range(max_length_targ):
    predictions, dec_hidden, attention_weights = decoder(dec_input,
                                                         dec_hidden,
                                                         enc_out)
    # storing the attention weights to plot later on
    attention_weights = tf.reshape(attention_weights, (-1, ))
    attention_plot[t] = attention_weights.numpy()
    predicted_id = tf.argmax(predictions[0]).numpy()

    result += targ_lang.index_word[predicted_id] + ' '

    if targ_lang.index_word[predicted_id] == '<end>':
      return result,attention_plot

    # the predicted ID is fed back into the model
    dec_input = tf.expand_dims([predicted_id], 0)

  return result,attention_plot

In [9]:
input_sentence= 'please ensure that you use the appropriate form '
print('Input sentence in english : ',input_sentence)
predicted_output,attention_plot=evaluate1(input_sentence)
print('Predicted sentence in telugu : ',predicted_output)

Input sentence in english :  please ensure that you use the appropriate form 


NameError: name 'translator' is not defined

In [ ]:
input_sentence='and do something with it to change the world '
print('Input sentence in english : ',input_sentence)
predicted_output,attention_plot=evaluate(input_sentence)
print('Predicted sentence in telugu : ',predicted_output)